# Generated by Django 4.2.9 on 2025-01-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('long_description', models.TextField(verbose_name='Описание')),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=17, verbose_name='Долгота')),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=17, verbose_name='Широта')),
            ],
        ),
    ]
