# Generated by Django 4.2.9 on 2025-01-25 04:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_image_options_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='long_description',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
    ]
