# Generated by Django 4.2.9 on 2025-03-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_image_order_alter_place_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Номер'),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('title', 'longitude', 'latitude')},
        ),
    ]
